#!/usr/bin/env python

x = input("I am thinking of a number between 40 and 50:\n")

print("You entered:")
print(x)

secret = 42

if x == secret:
    print("CORRECT!!")
else:
    print("Whaa whaa whaa!!")

# end of file
